Repository kubernetes-sigs/windows-gmsa, pull requests merged in 2019-03, with the labels that each got.

#2 Enabling travis builds for the webhook
  .travis.yml
  README.md
  admission-webhook/webhook.go
  admission-webhook/webhook_http_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#3 Adding dockerfiles and install scripts
  admission-webhook/Makefile
  admission-webhook/README.md
  admission-webhook/deploy/.helpers.sh
  admission-webhook/deploy/create-signed-cert.sh
  admission-webhook/deploy/deploy-gmsa-webhook.sh
  admission-webhook/deploy/gmsa-webhook.yml.tpl
  admission-webhook/dockerfiles/Dockerfile
  admission-webhook/dockerfiles/Dockerfile.dev
  admission-webhook/main.go
  admission-webhook/make/deps.mk
  admission-webhook/make/image.mk
Labels: approved, cncf-cla: yes, lgtm, size/XL

#4 Adding extensive integration tests
  .travis.yml
  admission-webhook/.gitignore
  admission-webhook/.travis.sh
  admission-webhook/Makefile
  admission-webhook/deploy/.helpers.sh
  admission-webhook/deploy/create-signed-cert.sh
  admission-webhook/deploy/deploy-gmsa-webhook.sh
  admission-webhook/deploy/gmsa-webhook.yml.tpl
  admission-webhook/dockerfiles/Dockerfile
  admission-webhook/dockerfiles/Dockerfile.dev
  admission-webhook/glide.lock
  admission-webhook/integration_tests/integration_test.go
  admission-webhook/integration_tests/kube.go
  admission-webhook/integration_tests/templates/all-credspecs-users-rbac-role.yml
  admission-webhook/integration_tests/templates/credspec-0.yml
  admission-webhook/integration_tests/templates/credspec-1.yml
  admission-webhook/integration_tests/templates/credspec-2.yml
  admission-webhook/integration_tests/templates/credspecs-users-rbac-role.yml
  admission-webhook/integration_tests/templates/happy-path-with-pre-set-matching-annotations.yml
  admission-webhook/integration_tests/templates/sa-rbac-binding.yml
  admission-webhook/integration_tests/templates/service-account.yml
  admission-webhook/integration_tests/templates/several-containers-with-gmsa.yml
  admission-webhook/integration_tests/templates/simple-with-container-level-gmsa.yml
  admission-webhook/integration_tests/templates/simple-with-gmsa.yml
  admission-webhook/integration_tests/templates/simple-with-preset-gmsa-container-level-contents-annotation.yml
  admission-webhook/integration_tests/templates/simple-with-preset-gmsa-pod-level-contents-annotation.yml
  admission-webhook/integration_tests/templates/simple-with-unknown-gmsa.yml
  admission-webhook/integration_tests/templates/single-pod-with-container-level-gmsa.yml
  admission-webhook/integration_tests/templates/single-pod-with-gmsa.yml
  admission-webhook/integration_tests/utils.go
  admission-webhook/make/deps.mk
  admission-webhook/make/dev_cluster.mk
  admission-webhook/make/image.mk
  admission-webhook/version.go
  admission-webhook/webhook.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#5 Fixing a small bug in the deploy script
  .travis.yml
  admission-webhook/.travis.sh
  admission-webhook/deploy/.helpers.sh
  admission-webhook/deploy/create-signed-cert.sh
  admission-webhook/deploy/deploy-gmsa-webhook.sh
Labels: approved, cncf-cla: yes, lgtm, sig/windows, size/M

#7 Adding myself (wk8) to OWNERS
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8 Add the GMSA CRD YAML
  CRD/gmsa-crd.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#9 Consolidating the CRD definition in one place
  admission-webhook/deploy/deploy-gmsa-webhook.sh
  admission-webhook/deploy/gmsa-crd.yml
  admission-webhook/deploy/gmsa-webhook.yml.tpl
Labels: approved, cncf-cla: yes, lgtm, size/S

#10 Adding a powershell script to generate GMSA resource manifests
  scripts/GenerateCredentialSpecResource.ps1
Labels: approved, cncf-cla: yes, lgtm, size/M
