Repository kubernetes-sigs/windows-gmsa, pull requests merged in 2021-05, with the labels that each got.

#29 update spec
  admission-webhook/deploy/create-signed-cert.sh
  admission-webhook/deploy/gmsa-crd.yml
  admission-webhook/deploy/gmsa-webhook.yml.tpl
Labels: approved, cncf-cla: yes, lgtm, size/M

#35 Update tooling
  .github/actions/tests/action.yaml
  .github/workflows/build.yaml
  .gitignore
  .travis.yml
  README.md
  admission-webhook/Makefile
  admission-webhook/deploy/deploy-gmsa-webhook.sh
  admission-webhook/dockerfiles/Dockerfile
  admission-webhook/glide.lock
  admission-webhook/glide.yaml
  admission-webhook/go.mod
  admission-webhook/go.sum
  admission-webhook/make/deps.mk
  admission-webhook/make/dev_cluster.mk
  admission-webhook/make/image.mk
  admission-webhook/make/start_cluster.sh
  admission-webhook/run-ci.sh
Labels: approved, cncf-cla: yes, size/XXL

#36 Update CI to work in github actions hosted env
  .github/actions/tests/action.yaml
Labels: approved, cncf-cla: yes, size/XS

#37 Update k8s dependencies
  admission-webhook/Makefile
  admission-webhook/go.mod
  admission-webhook/go.sum
  admission-webhook/integration_tests/integration_test.go
  admission-webhook/integration_tests/kube.go
  admission-webhook/kube_client.go
  admission-webhook/make/deps.mk
  admission-webhook/make/dev_cluster.mk
  admission-webhook/types.go
  admission-webhook/utils_test.go
  admission-webhook/webhook.go
  admission-webhook/webhook_http_test.go
  admission-webhook/webhook_test.go
Labels: approved, cncf-cla: yes, size/XL

#38 Use githubs envs instead of travis ci
  admission-webhook/make/dev_cluster.mk
  admission-webhook/run-ci.sh
Labels: approved, cncf-cla: yes, size/S
