Repository kubernetes-sigs/windows-gmsa, pull requests merged in 2022-02, with the labels that each got.

#57 Adding the ability to configure the webhook port.
  admission-webhook/main.go
Labels: ok-to-test, lgtm, approved, cncf-cla: yes, size/S

#58 Update k8s deps and go build version
  .github/workflows/build.yaml
  admission-webhook/go.mod
  admission-webhook/go.sum
  admission-webhook/make/image.mk
Labels: lgtm, approved, cncf-cla: yes, size/XL

#59 Updating makefiles so we can push staging images to gcr.io/k8s-staging/gmsa-webhook
  admission-webhook/Makefile
  admission-webhook/make/dev_cluster.mk
  admission-webhook/make/image.mk
  cloudbuild.yaml
Labels: lgtm, approved, size/M, cncf-cla: yes

#61 Updating release.md
  OWNERS
  RELEASE.md
Labels: lgtm, approved, size/M, cncf-cla: yes

#63 Fix to allow for TAG to be inherited from env in the makefiles
  admission-webhook/Makefile
  cloudbuild.yaml
Labels: sig/windows, lgtm, approved, cncf-cla: yes, size/XS

#64 Updating cloudbuild.yaml again
  cloudbuild.yaml
Labels: sig/windows, approved, cncf-cla: yes, size/XS

#65 docs: Updating RELEASE.md with image promotion instructions
  RELEASE.md
Labels: sig/windows, lgtm, approved, cncf-cla: yes, size/S

#66 EKS installation doc updates
  admission-webhook/README.md
Labels: sig/windows, lgtm, approved, cncf-cla: yes, size/XS
