Repository kubernetes-sigs/windows-gmsa, pull requests merged in 2023-08, with the labels that each got.

#115 Update dependencies
  admission-webhook/go.mod
  admission-webhook/go.sum
Labels: sig/windows, lgtm, approved, size/L, cncf-cla: yes

#116 Update to go 1.21
  .github/workflows/build.yaml
  admission-webhook/go.mod
  admission-webhook/go.sum
  admission-webhook/make/image.mk
Labels: sig/windows, lgtm, approved, cncf-cla: yes, size/S

#118 call gcloud auth in cloudbuild.yaml
  cloudbuild.yaml
Labels: sig/windows, lgtm, approved, cncf-cla: yes, size/XS

#120 Adding an issue template for cutting new releases
  .github/ISSUE_TEMPLATE/new-release.md
  RELEASE.md
Labels: sig/windows, lgtm, approved, size/M, cncf-cla: yes

#121 Misc updates for releasing v0.7.0 image
  admission-webhook/deploy/deploy-gmsa-webhook.sh
  charts/gmsa/Chart.yaml
  charts/gmsa/templates/credentialspec.yaml
  charts/gmsa/values.yaml
  charts/repo/gmsa-0.7.1.tgz
  charts/repo/gmsa-0.7.2.tgz
  charts/repo/index.yaml
Labels: sig/windows, lgtm, approved, size/M, cncf-cla: yes

#122 fix kubeconfig issue in dev_cluster.mk
  admission-webhook/make/dev_cluster.mk
Labels: sig/windows, lgtm, approved, cncf-cla: yes, size/XS
