Repository kubernetes-sigs/windows-gmsa, pull requests merged in 2023-05, with the labels that each got.

#105 Bump dependency versions
  admission-webhook/go.mod
  admission-webhook/go.sum
Labels: sig/windows, lgtm, approved, size/L, cncf-cla: yes

#106 Update to golang 1.20
  .github/workflows/build.yaml
  admission-webhook/go.mod
  admission-webhook/make/image.mk
Labels: sig/windows, lgtm, approved, cncf-cla: yes, size/S

#108 Use dl.k8s.io instead of kubernetes-release bucket
  admission-webhook/make/dev_cluster.mk
Labels: sig/windows, lgtm, approved, cncf-cla: yes, size/XS
