Repository kubernetes-sigs/windows-gmsa, pull requests merged in 2024-03, with the labels that each got.

#141 Watch cert files and reload on change
  admission-webhook/cert_reloader.go
  admission-webhook/cert_reloader_test.go
  admission-webhook/go.mod
  admission-webhook/go.sum
  admission-webhook/integration_tests/integration_test.go
  admission-webhook/integration_tests/templates/new-secret.yml
  admission-webhook/main.go
  admission-webhook/testdata/cert.pem
  admission-webhook/testdata/key.pem
  admission-webhook/webhook.go
  admission-webhook/webhook_http_test.go
  admission-webhook/webhook_test.go
  charts/README.md
  charts/gmsa/templates/deployment.yaml
  charts/gmsa/values.yaml
Labels: ok-to-test, sig/windows, lgtm, approved, size/L, cncf-cla: yes

#142 Integration tests wasn't running
  admission-webhook/run-ci.sh
Labels: sig/windows, lgtm, approved, cncf-cla: yes, size/XS

#143 Update kind, cert-manager, and helm versions
  admission-webhook/make/dev_cluster.mk
  admission-webhook/make/helm.mk
Labels: sig/windows, lgtm, approved, cncf-cla: yes, size/XS

#146 Use dev image instead of published image
  admission-webhook/make/dev_cluster.mk
  admission-webhook/make/helm.mk
Labels: sig/windows, lgtm, approved, cncf-cla: yes, size/S

#145 Cert rotation for e2e chart
  .github/workflows/build.yaml
  admission-webhook/cert_reloader.go
  admission-webhook/cert_reloader_test.go
  admission-webhook/integration_tests/integration_test.go
  admission-webhook/make/helm.mk
  admission-webhook/webhook.go
  charts/gmsa/templates/issuer.yaml
  charts/gmsa/templates/mutatingwebhook.yaml
  charts/gmsa/templates/validatingwebhook.yaml
Labels: sig/windows, lgtm, approved, size/L, cncf-cla: yes
